### ISSUE TITLE
Add support for opensuse?

### ISSUE THREAD

**Issue by jkroepke** [voxpupuli/beaker#1698]
Currently beaker-hostgenerator supports opensuse well. but beaker-rspec not.

If opensuse15-64 is selected as platform, I got an error

>   Unsupported platform name opensuse-15-x86_64

https://www.travis-ci.com/github/jkroepke/puppet-module-autofs/jobs/502897451

Since RedHat decide deprecate CentOS in favor of CentOS Stream, OpenSuse gets more interests.

**Comment by ekohl** [comment]
This is the first time I used the transfer issue task but it appears to have done what it's supposed to. Can you confirm this?

**Comment by jkroepke** [comment]
Yes, thanks.
